build:
    environment:
        php: '5.5.25'
    tests:
        override:
            command: 'phpunit --coverage-clover=test-results'
            coverage:
                file: 'test-results'
                format: 'clover'