language: php

matrix:
  fast_finish: true
  include:
    - php: 7.2
    - php: 7.3
    - php: 7.4

install:
  - composer install

script:
  - ./vendor/bin/phpunit --coverage-clover=./coverage.clover
