language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

env:
  - GUZZLE_VERSION="~5.0"
  - GUZZLE_VERSION="~6.0"

install:
  - composer install
  - composer require guzzlehttp/guzzle:${GUZZLE_VERSION}

script:
  - sh ./bin/check_code_style.sh