language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - GUZZLE_VERSION="~5.0"
  - GUZZLE_VERSION="~6.0"

install:
  - composer config platform.php $TRAVIS_PHP_VERSION
  - cat composer.json
  - composer install
  - composer require guzzlehttp/guzzle:${GUZZLE_VERSION}

script:
  - sh ./bin/check_code_style.sh
  - ./vendor/bin/phpunit