language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'

env:
  - GUZZLE_VERSION="5.0"
  - GUZZLE_VERSION="6.0"

install:
  - composer install
  - composer require guzzlehttp/guzzle:^${GUZZLE_VERSION}
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - sh ./bin/check_code_style.sh
  - ./vendor/bin/phpunit --coverage-clover=./coverage.clover
  - php ocular.phar code-coverage:upload --format=php-clover ./coverage.clover